name: Deploy Sequentially to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy-server-1:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Home Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_HOME }}
          username: ${{ secrets.SERVER_USER_HOME }}
          key: ${{ secrets.SERVER_SSH_KEY_HOME }}
          script: |
            cd /var/www/sebringautomotive.shop
            /usr/bin/git config --global --add safe.directory /var/www/sebringautomotive.shop
            /usr/bin/git pull
            /usr/bin/sudo chown -R www-data:www-data .
            echo "Deployment to Home Server complete!"

  deploy-server-2:
    needs: deploy-server-1
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCloud Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_GCLOUD }}
          username: ${{ secrets.SERVER_USER_GCLOUD }}
          key: ${{ secrets.SERVER_SSH_KEY_GCLOUD }}
          script: |
            cd /var/www/html
            /usr/bin/git config --global --add safe.directory /var/www/html
            /usr/bin/git pull
            /usr/bin/sudo chown -R www-data:www-data .
            echo "Deployment to GCloud Server complete!"