name: Deploy Sequentially to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy-server-1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY_HOME }}
      
      - name: Deploy to Home Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_HOME }}@${{ secrets.SERVER_HOST_HOME }} '
            cd /var/www/sebringautomotive.shop &&
            /usr/bin/git config --global --add safe.directory /var/www/sebringautomotive.shop &&
            /usr/bin/git pull &&
            /usr/bin/sudo chown -R www-data:www-data . &&
            echo "Deployment to Home Server complete!"
          '

  deploy-server-2:
    needs: deploy-server-1
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY_GCLOUD }}

      - name: Deploy to GCloud Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_GCLOUD }}@${{ secrets.SERVER_HOST_GCLOUD }} '
            cd /var/www/html &&
            /usr/bin/git config --global --add safe.directory /var/www/html &&
            /usr/bin/git pull &&
            /usr/bin/sudo chown -R www-data:www-data . &&
            echo "Deployment to GCloud Server complete!"
          '